Algoritmo "ex_circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/07/2022
Var

   raio, area : real

Inicio

   escreva("Digite o valor do raio do circulo: ")
   leia(raio)
   
   area <- pi * exp(raio, 2)
   
   escreva("Area: ", area:8:3)


Fimalgoritmo